#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# autostart system tray apps
exec-once = nm-applet & blueman-applet &

# autostart applications
# exec-once = brave-browser & 1password --silent & init_tmux.sh & slack & firefox &  
exec-once = brave-browser &

# autostart hyprland components
exec-once = waybar & hyprpaper & hypridle

exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
exec = gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Ice"
exec = gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
#exec =   security.pam.services.greetd.enableGnomeKeyring = true

# Update tmux environment 
exec-once = tmux setenv -g HYPRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"
