###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$browser = brave-browser --password-store=gnome-libsecret
$webapp = $browser --app
$menu = rofi -show drun
$powermenu = ~/.config/rofi/powermenu/powermenu.sh
$lock = hyprlock

$monitorLeft = DP-3
$monitorRight = DP-5
$monitorBuiltin = eDP-1


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = XCURSOR_PATH,~/.local/share/icons
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24
env = AQ_NO_MODIFIERS,1
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = JAVA_HOME,/usr/lib64/jvm/java-11-openjdk-11
