##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# floating brave open file picker dialog
windowrule = float on,match:class brave,match:title .*wants to open.*
windowrule = center on,match:class brave,match:title .*wants to open.*
windowrule = size 1150 750,match:class brave,match:title .*wants to open.*

# floating brave save file picker dialog
windowrule = float on,match:class brave,match:title .*wants to save.*
windowrule = center on,match:class brave,match:title .*wants to save.*
windowrule = size 1150 750,match:class brave,match:title .*wants to save.*


# windowrule = suppressevent maximize, class:.* # You'll probably like this.
# windowrule = noblur,class:^()$,title:^()$
